// <auto-generated />
namespace FYP.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class April18F : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(April18F));
        
        string IMigrationMetadata.Id
        {
            get { return "201704181639267_April18F"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
