// <auto-generated />
namespace FYP.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class ap_302 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ap_302));
        
        string IMigrationMetadata.Id
        {
            get { return "201704292022105_ap_302"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
